language: elixir
elixir:
  - 1.3.1
otp_release:
  - 19
sudo: required
install:
  - mix deps.get
script:
  - mix test
after_script:
  - mix deps.get --only docs
notifications:
  recipients:
    - kabasakalis@gmail.com
